### ISSUE TITLE
[db-branch] Schema for MongoDB

### ISSUE THREAD

**Issue by Vanshika-73** [LuciAkirami/express-rest-api#4]
Will create a schema for sample data.

**Comment by Vanshika-73** [comment]
Lets say will create a schema for a teacher or school to maintain student's record.

**Comment by LuciAkirami** [comment]
For now, let's store the data in a json file. Later, we can add the database. The data in json file will be a list of the following object. Let's go universities

```
{
  id: "a unique id",
  name: "name of university",
  location: {city:"city of university", country: "country the university located at"},
  programs: "a list of programs offered by the uni, eg: [Computer Science, AeroSpace, Law] etc"
}
```

So let's create some dummy data that follows the above schema and add it to a json named "university.json"

**Comment by Vanshika-73** [comment]
okay, please assign this task to me under hacktoberfest.

**Comment by LuciAkirami** [comment]
Assigning this to you. You can create a pull request to the `db-branch`. 

Please change the Issue name to "[db-branch]Schema for MongoDB", and please add the "[db-branch]" prefix to all other issues as well

**Comment by LuciAkirami** [comment]
@Vanshika-73 , you can check the `data/university.json` in `json-branch`, for the sample data/schema of the data, so that you can create that schema in a database.

**Comment by Vanshika-73** [comment]
i have to code in main branch? mean i should create pr for which branch?
