### ISSUE TITLE
[db-branch] function to add sample data to db.

### ISSUE THREAD

**Issue by Vanshika-73** [LuciAkirami/express-rest-api#5]
Will create basic simple function to add data that will be called only once. (require MongoUrl for it).

**Comment by LuciAkirami** [comment]
How about creating two branches of this repo, one branch that uses university.json, one branch will be using a database

**Comment by Vanshika-73** [comment]
oh okay, but how will you test operations on json file?

**Comment by LuciAkirami** [comment]
Like you have mentioned in the other issue, either with Postman or Thunderclient. I will be using thunderclient to test the API, mainly testing the CRUD operations performed on the JSON file. 

Assigning this issue to you, you can fork the repo and after working on it, you can create a pull request to merge wit the `db-branch`

**Comment by Vanshika-73** [comment]
hey, Where to insert data?😅 Should i use my own mongodb url?

**Comment by LuciAkirami** [comment]
Yah. For now also create a sample js file (call it some data_adder) that adds some 4-5 data points to the DB.  So that when I run this data_addr.js with my credentials, the data will get added to my local MongoDB
