### ISSUE TITLE
[db-branch] CRUD operations.

### ISSUE THREAD

**Issue by Vanshika-73** [LuciAkirami/express-rest-api#6]
Will create basic crud operations for the same model

**Comment by LuciAkirami** [comment]
yup, creating these in separate files will be better, from a readability perspective. So how would you want to structure it?, would you be writing all CRUD operations in a single file or in multiple files ? i.e. one file per operation?

**Comment by Vanshika-73** [comment]
no, i used to create a single file for all 4operations but under a different folder. like different folders for routes, modals and controllers.

**Comment by LuciAkirami** [comment]
ok, maybe we can touch upon refactoring the code later
